package model;
// Generated Jan 6, 2017 6:14:38 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Atributo generated by hbm2java
 */
public class Atributo  implements java.io.Serializable {


     private Integer idAtributo;
     private Tipo tipo;
     private String nomeAtributo;
     private Character tipoDado;
     private BigDecimal tamDado;
     private Character stAtributo;
     private Boolean flObrig;
     private Set<VendaItemAtributo> vendaItemAtributos = new HashSet<VendaItemAtributo>(0);
     private Set<ProdutoAtributo> produtoAtributos = new HashSet<ProdutoAtributo>(0);

    public Atributo() {
    }

    public Atributo(Tipo tipo, String nomeAtributo, Character tipoDado, BigDecimal tamDado, Character stAtributo, Boolean flObrig, Set<VendaItemAtributo> vendaItemAtributos, Set<ProdutoAtributo> produtoAtributos) {
       this.tipo = tipo;
       this.nomeAtributo = nomeAtributo;
       this.tipoDado = tipoDado;
       this.tamDado = tamDado;
       this.stAtributo = stAtributo;
       this.flObrig = flObrig;
       this.vendaItemAtributos = vendaItemAtributos;
       this.produtoAtributos = produtoAtributos;
    }
   
    public Integer getIdAtributo() {
        return this.idAtributo;
    }
    
    public void setIdAtributo(Integer idAtributo) {
        this.idAtributo = idAtributo;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public String getNomeAtributo() {
        return this.nomeAtributo;
    }
    
    public void setNomeAtributo(String nomeAtributo) {
        this.nomeAtributo = nomeAtributo;
    }
    public Character getTipoDado() {
        return this.tipoDado;
    }
    
    public void setTipoDado(Character tipoDado) {
        this.tipoDado = tipoDado;
    }
    public BigDecimal getTamDado() {
        return this.tamDado;
    }
    
    public void setTamDado(BigDecimal tamDado) {
        this.tamDado = tamDado;
    }
    public Character getStAtributo() {
        return this.stAtributo;
    }
    
    public void setStAtributo(Character stAtributo) {
        this.stAtributo = stAtributo;
    }
    public Boolean getFlObrig() {
        return this.flObrig;
    }
    
    public void setFlObrig(Boolean flObrig) {
        this.flObrig = flObrig;
    }
    public Set<VendaItemAtributo> getVendaItemAtributos() {
        return this.vendaItemAtributos;
    }
    
    public void setVendaItemAtributos(Set<VendaItemAtributo> vendaItemAtributos) {
        this.vendaItemAtributos = vendaItemAtributos;
    }
    public Set<ProdutoAtributo> getProdutoAtributos() {
        return this.produtoAtributos;
    }
    
    public void setProdutoAtributos(Set<ProdutoAtributo> produtoAtributos) {
        this.produtoAtributos = produtoAtributos;
    }




}


