package model;
// Generated Dec 13, 2016 10:09:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Atributo generated by hbm2java
 */
public class Atributo  implements java.io.Serializable {


     private Integer idAtributo;
     private Tipo tipo;
     private String nomeAtributo;
     private Set<ValorAtributo> valorAtributos = new HashSet<ValorAtributo>(0);

    public Atributo() {
    }

	
    public Atributo(Tipo tipo, String nomeAtributo) {
        this.tipo = tipo;
        this.nomeAtributo = nomeAtributo;
    }
    public Atributo(Tipo tipo, String nomeAtributo, Set<ValorAtributo> valorAtributos) {
       this.tipo = tipo;
       this.nomeAtributo = nomeAtributo;
       this.valorAtributos = valorAtributos;
    }
   
    public Integer getIdAtributo() {
        return this.idAtributo;
    }
    
    public void setIdAtributo(Integer idAtributo) {
        this.idAtributo = idAtributo;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public String getNomeAtributo() {
        return this.nomeAtributo;
    }
    
    public void setNomeAtributo(String nomeAtributo) {
        this.nomeAtributo = nomeAtributo;
    }
    public Set<ValorAtributo> getValorAtributos() {
        return this.valorAtributos;
    }
    
    public void setValorAtributos(Set<ValorAtributo> valorAtributos) {
        this.valorAtributos = valorAtributos;
    }




}


