package model;
// Generated Dec 13, 2016 10:09:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer idCategoria;
     private String nomeCategoria;
     private Set<Produto> produtos = new HashSet<Produto>(0);
     private Set<Tipo> tipos = new HashSet<Tipo>(0);

    public Categoria() {
    }

	
    public Categoria(String nomeCategoria) {
        this.nomeCategoria = nomeCategoria;
    }
    public Categoria(String nomeCategoria, Set<Produto> produtos, Set<Tipo> tipos) {
       this.nomeCategoria = nomeCategoria;
       this.produtos = produtos;
       this.tipos = tipos;
    }
   
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNomeCategoria() {
        return this.nomeCategoria;
    }
    
    public void setNomeCategoria(String nomeCategoria) {
        this.nomeCategoria = nomeCategoria;
    }
    public Set<Produto> getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set<Produto> produtos) {
        this.produtos = produtos;
    }
    public Set<Tipo> getTipos() {
        return this.tipos;
    }
    
    public void setTipos(Set<Tipo> tipos) {
        this.tipos = tipos;
    }




}


