package model;
// Generated Dec 13, 2016 10:09:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ClientePf generated by hbm2java
 */
public class ClientePf  implements java.io.Serializable {


     private Integer idClientePf;
     private String nome;
     private String sobrenome;
     private String cpf;
     private int idEndereco;
     private Character sexo;
     private Integer status;
     private Set<Contato> contatos = new HashSet<Contato>(0);
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public ClientePf() {
    }

	
    public ClientePf(String cpf, int idEndereco) {
        this.cpf = cpf;
        this.idEndereco = idEndereco;
    }
    public ClientePf(String nome, String sobrenome, String cpf, int idEndereco, Character sexo, Integer status, Set<Contato> contatos, Set<Pedido> pedidos) {
       this.nome = nome;
       this.sobrenome = sobrenome;
       this.cpf = cpf;
       this.idEndereco = idEndereco;
       this.sexo = sexo;
       this.status = status;
       this.contatos = contatos;
       this.pedidos = pedidos;
    }
   
    public Integer getIdClientePf() {
        return this.idClientePf;
    }
    
    public void setIdClientePf(Integer idClientePf) {
        this.idClientePf = idClientePf;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public int getIdEndereco() {
        return this.idEndereco;
    }
    
    public void setIdEndereco(int idEndereco) {
        this.idEndereco = idEndereco;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set<Contato> getContatos() {
        return this.contatos;
    }
    
    public void setContatos(Set<Contato> contatos) {
        this.contatos = contatos;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


