package model;
// Generated Dec 13, 2016 10:09:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ClientePj generated by hbm2java
 */
public class ClientePj  implements java.io.Serializable {


     private Integer idClientePj;
     private Endereco endereco;
     private String nomeFantasia;
     private String razaoSocial;
     private Long inscricaoEstadual;
     private long cnpj;
     private Integer status;
     private Set<Contato> contatos = new HashSet<Contato>(0);
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public ClientePj() {
    }

	
    public ClientePj(Endereco endereco, long cnpj) {
        this.endereco = endereco;
        this.cnpj = cnpj;
    }
    public ClientePj(Endereco endereco, String nomeFantasia, String razaoSocial, Long inscricaoEstadual, long cnpj, Integer status, Set<Contato> contatos, Set<Pedido> pedidos) {
       this.endereco = endereco;
       this.nomeFantasia = nomeFantasia;
       this.razaoSocial = razaoSocial;
       this.inscricaoEstadual = inscricaoEstadual;
       this.cnpj = cnpj;
       this.status = status;
       this.contatos = contatos;
       this.pedidos = pedidos;
    }
   
    public Integer getIdClientePj() {
        return this.idClientePj;
    }
    
    public void setIdClientePj(Integer idClientePj) {
        this.idClientePj = idClientePj;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public String getNomeFantasia() {
        return this.nomeFantasia;
    }
    
    public void setNomeFantasia(String nomeFantasia) {
        this.nomeFantasia = nomeFantasia;
    }
    public String getRazaoSocial() {
        return this.razaoSocial;
    }
    
    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }
    public Long getInscricaoEstadual() {
        return this.inscricaoEstadual;
    }
    
    public void setInscricaoEstadual(Long inscricaoEstadual) {
        this.inscricaoEstadual = inscricaoEstadual;
    }
    public long getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(long cnpj) {
        this.cnpj = cnpj;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set<Contato> getContatos() {
        return this.contatos;
    }
    
    public void setContatos(Set<Contato> contatos) {
        this.contatos = contatos;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


