package model;
// Generated Dec 13, 2016 10:09:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Contato generated by hbm2java
 */
public class Contato  implements java.io.Serializable {


     private Integer idContato;
     private ClientePf clientePf;
     private ClientePj clientePj;
     private Integer ddd;
     private Integer contato;
     private String email;
     private Set<Fornecedor> fornecedors = new HashSet<Fornecedor>(0);

    public Contato() {
    }

    public Contato(ClientePf clientePf, ClientePj clientePj, Integer ddd, Integer contato, String email, Set<Fornecedor> fornecedors) {
       this.clientePf = clientePf;
       this.clientePj = clientePj;
       this.ddd = ddd;
       this.contato = contato;
       this.email = email;
       this.fornecedors = fornecedors;
    }
   
    public Integer getIdContato() {
        return this.idContato;
    }
    
    public void setIdContato(Integer idContato) {
        this.idContato = idContato;
    }
    public ClientePf getClientePf() {
        return this.clientePf;
    }
    
    public void setClientePf(ClientePf clientePf) {
        this.clientePf = clientePf;
    }
    public ClientePj getClientePj() {
        return this.clientePj;
    }
    
    public void setClientePj(ClientePj clientePj) {
        this.clientePj = clientePj;
    }
    public Integer getDdd() {
        return this.ddd;
    }
    
    public void setDdd(Integer ddd) {
        this.ddd = ddd;
    }
    public Integer getContato() {
        return this.contato;
    }
    
    public void setContato(Integer contato) {
        this.contato = contato;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Fornecedor> getFornecedors() {
        return this.fornecedors;
    }
    
    public void setFornecedors(Set<Fornecedor> fornecedors) {
        this.fornecedors = fornecedors;
    }




}


