package model;
// Generated Dec 13, 2016 10:09:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Endereco generated by hbm2java
 */
public class Endereco  implements java.io.Serializable {


     private Integer idEndereco;
     private String cep;
     private String nomeRua;
     private String bairro;
     private String cidade;
     private String pais;
     private String estado;
     private Integer numero;
     private String complemento;
     private Set<Fornecedor> fornecedors = new HashSet<Fornecedor>(0);
     private Set<ClientePj> clientePjs = new HashSet<ClientePj>(0);

    public Endereco() {
    }

    public Endereco(String cep, String nomeRua, String bairro, String cidade, String pais, String estado, Integer numero, String complemento, Set<Fornecedor> fornecedors, Set<ClientePj> clientePjs) {
       this.cep = cep;
       this.nomeRua = nomeRua;
       this.bairro = bairro;
       this.cidade = cidade;
       this.pais = pais;
       this.estado = estado;
       this.numero = numero;
       this.complemento = complemento;
       this.fornecedors = fornecedors;
       this.clientePjs = clientePjs;
    }
   
    public Integer getIdEndereco() {
        return this.idEndereco;
    }
    
    public void setIdEndereco(Integer idEndereco) {
        this.idEndereco = idEndereco;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getNomeRua() {
        return this.nomeRua;
    }
    
    public void setNomeRua(String nomeRua) {
        this.nomeRua = nomeRua;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public Set<Fornecedor> getFornecedors() {
        return this.fornecedors;
    }
    
    public void setFornecedors(Set<Fornecedor> fornecedors) {
        this.fornecedors = fornecedors;
    }
    public Set<ClientePj> getClientePjs() {
        return this.clientePjs;
    }
    
    public void setClientePjs(Set<ClientePj> clientePjs) {
        this.clientePjs = clientePjs;
    }




}


