package model;
// Generated Jan 6, 2017 6:14:38 PM by Hibernate Tools 4.3.1



/**
 * Endereco generated by hbm2java
 */
public class Endereco  implements java.io.Serializable {


     private int idEndereco;
     private Pessoa pessoa;
     private char tipoEndereco;
     private String cep;
     private String nomeRua;
     private String bairro;
     private String cidade;
     private String pais;
     private String estado;
     private Integer numero;
     private String complemento;

    public Endereco() {
    }

	
    public Endereco(int idEndereco, Pessoa pessoa, char tipoEndereco) {
        this.idEndereco = idEndereco;
        this.pessoa = pessoa;
        this.tipoEndereco = tipoEndereco;
    }
    public Endereco(int idEndereco, Pessoa pessoa, char tipoEndereco, String cep, String nomeRua, String bairro, String cidade, String pais, String estado, Integer numero, String complemento) {
       this.idEndereco = idEndereco;
       this.pessoa = pessoa;
       this.tipoEndereco = tipoEndereco;
       this.cep = cep;
       this.nomeRua = nomeRua;
       this.bairro = bairro;
       this.cidade = cidade;
       this.pais = pais;
       this.estado = estado;
       this.numero = numero;
       this.complemento = complemento;
    }
   
    public int getIdEndereco() {
        return this.idEndereco;
    }
    
    public void setIdEndereco(int idEndereco) {
        this.idEndereco = idEndereco;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public char getTipoEndereco() {
        return this.tipoEndereco;
    }
    
    public void setTipoEndereco(char tipoEndereco) {
        this.tipoEndereco = tipoEndereco;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getNomeRua() {
        return this.nomeRua;
    }
    
    public void setNomeRua(String nomeRua) {
        this.nomeRua = nomeRua;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }




}


