package model;
// Generated Jan 6, 2017 6:14:38 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Estoque generated by hbm2java
 */
public class Estoque  implements java.io.Serializable {


     private EstoqueId id;
     private Produto produto;
     private Date dtFim;
     private BigDecimal qtdAnterior;
     private BigDecimal qtdEntrada;
     private BigDecimal qtdSaida;
     private BigDecimal qtdFinal;

    public Estoque() {
    }

	
    public Estoque(EstoqueId id, Produto produto) {
        this.id = id;
        this.produto = produto;
    }
    public Estoque(EstoqueId id, Produto produto, Date dtFim, BigDecimal qtdAnterior, BigDecimal qtdEntrada, BigDecimal qtdSaida, BigDecimal qtdFinal) {
       this.id = id;
       this.produto = produto;
       this.dtFim = dtFim;
       this.qtdAnterior = qtdAnterior;
       this.qtdEntrada = qtdEntrada;
       this.qtdSaida = qtdSaida;
       this.qtdFinal = qtdFinal;
    }
   
    public EstoqueId getId() {
        return this.id;
    }
    
    public void setId(EstoqueId id) {
        this.id = id;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Date getDtFim() {
        return this.dtFim;
    }
    
    public void setDtFim(Date dtFim) {
        this.dtFim = dtFim;
    }
    public BigDecimal getQtdAnterior() {
        return this.qtdAnterior;
    }
    
    public void setQtdAnterior(BigDecimal qtdAnterior) {
        this.qtdAnterior = qtdAnterior;
    }
    public BigDecimal getQtdEntrada() {
        return this.qtdEntrada;
    }
    
    public void setQtdEntrada(BigDecimal qtdEntrada) {
        this.qtdEntrada = qtdEntrada;
    }
    public BigDecimal getQtdSaida() {
        return this.qtdSaida;
    }
    
    public void setQtdSaida(BigDecimal qtdSaida) {
        this.qtdSaida = qtdSaida;
    }
    public BigDecimal getQtdFinal() {
        return this.qtdFinal;
    }
    
    public void setQtdFinal(BigDecimal qtdFinal) {
        this.qtdFinal = qtdFinal;
    }




}


