package model;
// Generated Dec 13, 2016 10:09:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Estoque generated by hbm2java
 */
public class Estoque  implements java.io.Serializable {


     private Integer idEstoque;
     private Produto produto;
     private Integer qtdProduto;
     private Date dataEntrada;
     private Date dataSaida;
     private Set<ProdutosPedido> produtosPedidos = new HashSet<ProdutosPedido>(0);

    public Estoque() {
    }

	
    public Estoque(Produto produto, Date dataEntrada) {
        this.produto = produto;
        this.dataEntrada = dataEntrada;
    }
    public Estoque(Produto produto, Integer qtdProduto, Date dataEntrada, Date dataSaida, Set<ProdutosPedido> produtosPedidos) {
       this.produto = produto;
       this.qtdProduto = qtdProduto;
       this.dataEntrada = dataEntrada;
       this.dataSaida = dataSaida;
       this.produtosPedidos = produtosPedidos;
    }
   
    public Integer getIdEstoque() {
        return this.idEstoque;
    }
    
    public void setIdEstoque(Integer idEstoque) {
        this.idEstoque = idEstoque;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Integer getQtdProduto() {
        return this.qtdProduto;
    }
    
    public void setQtdProduto(Integer qtdProduto) {
        this.qtdProduto = qtdProduto;
    }
    public Date getDataEntrada() {
        return this.dataEntrada;
    }
    
    public void setDataEntrada(Date dataEntrada) {
        this.dataEntrada = dataEntrada;
    }
    public Date getDataSaida() {
        return this.dataSaida;
    }
    
    public void setDataSaida(Date dataSaida) {
        this.dataSaida = dataSaida;
    }
    public Set<ProdutosPedido> getProdutosPedidos() {
        return this.produtosPedidos;
    }
    
    public void setProdutosPedidos(Set<ProdutosPedido> produtosPedidos) {
        this.produtosPedidos = produtosPedidos;
    }




}


