package model;
// Generated Dec 13, 2016 10:09:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private Integer idFornecedor;
     private Contato contato;
     private Endereco endereco;
     private String nomeFantasia;
     private String razaoSocial;
     private int cnpj;
     private Set<Produto> produtos = new HashSet<Produto>(0);

    public Fornecedor() {
    }

	
    public Fornecedor(int cnpj) {
        this.cnpj = cnpj;
    }
    public Fornecedor(Contato contato, Endereco endereco, String nomeFantasia, String razaoSocial, int cnpj, Set<Produto> produtos) {
       this.contato = contato;
       this.endereco = endereco;
       this.nomeFantasia = nomeFantasia;
       this.razaoSocial = razaoSocial;
       this.cnpj = cnpj;
       this.produtos = produtos;
    }
   
    public Integer getIdFornecedor() {
        return this.idFornecedor;
    }
    
    public void setIdFornecedor(Integer idFornecedor) {
        this.idFornecedor = idFornecedor;
    }
    public Contato getContato() {
        return this.contato;
    }
    
    public void setContato(Contato contato) {
        this.contato = contato;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public String getNomeFantasia() {
        return this.nomeFantasia;
    }
    
    public void setNomeFantasia(String nomeFantasia) {
        this.nomeFantasia = nomeFantasia;
    }
    public String getRazaoSocial() {
        return this.razaoSocial;
    }
    
    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }
    public int getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(int cnpj) {
        this.cnpj = cnpj;
    }
    public Set<Produto> getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set<Produto> produtos) {
        this.produtos = produtos;
    }




}


