package model;
// Generated Jan 6, 2017 6:14:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private int idFornecedor;
     private Pessoa pessoa;
     private Set<Produto> produtos = new HashSet<Produto>(0);

    public Fornecedor() {
    }

	
    public Fornecedor(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Fornecedor(Pessoa pessoa, Set<Produto> produtos) {
       this.pessoa = pessoa;
       this.produtos = produtos;
    }
   
    public int getIdFornecedor() {
        return this.idFornecedor;
    }
    
    public void setIdFornecedor(int idFornecedor) {
        this.idFornecedor = idFornecedor;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Set<Produto> getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set<Produto> produtos) {
        this.produtos = produtos;
    }




}


