package model;
// Generated Dec 13, 2016 10:09:37 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer idPedido;
     private ClientePf clientePf;
     private ClientePj clientePj;
     private ProdutosPedido produtosPedido;
     private int idEndereco;
     private int idContato;
     private BigDecimal desconto;
     private Date dataCriacao;
     private Date dataDevolucao;
     private Date dataDevolucaoReal;
     private Set<ProdutosPedido> produtosPedidos = new HashSet<ProdutosPedido>(0);

    public Pedido() {
    }

	
    public Pedido(ProdutosPedido produtosPedido, int idEndereco, int idContato, Date dataCriacao) {
        this.produtosPedido = produtosPedido;
        this.idEndereco = idEndereco;
        this.idContato = idContato;
        this.dataCriacao = dataCriacao;
    }
    public Pedido(ClientePf clientePf, ClientePj clientePj, ProdutosPedido produtosPedido, int idEndereco, int idContato, BigDecimal desconto, Date dataCriacao, Date dataDevolucao, Date dataDevolucaoReal, Set<ProdutosPedido> produtosPedidos) {
       this.clientePf = clientePf;
       this.clientePj = clientePj;
       this.produtosPedido = produtosPedido;
       this.idEndereco = idEndereco;
       this.idContato = idContato;
       this.desconto = desconto;
       this.dataCriacao = dataCriacao;
       this.dataDevolucao = dataDevolucao;
       this.dataDevolucaoReal = dataDevolucaoReal;
       this.produtosPedidos = produtosPedidos;
    }
   
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public ClientePf getClientePf() {
        return this.clientePf;
    }
    
    public void setClientePf(ClientePf clientePf) {
        this.clientePf = clientePf;
    }
    public ClientePj getClientePj() {
        return this.clientePj;
    }
    
    public void setClientePj(ClientePj clientePj) {
        this.clientePj = clientePj;
    }
    public ProdutosPedido getProdutosPedido() {
        return this.produtosPedido;
    }
    
    public void setProdutosPedido(ProdutosPedido produtosPedido) {
        this.produtosPedido = produtosPedido;
    }
    public int getIdEndereco() {
        return this.idEndereco;
    }
    
    public void setIdEndereco(int idEndereco) {
        this.idEndereco = idEndereco;
    }
    public int getIdContato() {
        return this.idContato;
    }
    
    public void setIdContato(int idContato) {
        this.idContato = idContato;
    }
    public BigDecimal getDesconto() {
        return this.desconto;
    }
    
    public void setDesconto(BigDecimal desconto) {
        this.desconto = desconto;
    }
    public Date getDataCriacao() {
        return this.dataCriacao;
    }
    
    public void setDataCriacao(Date dataCriacao) {
        this.dataCriacao = dataCriacao;
    }
    public Date getDataDevolucao() {
        return this.dataDevolucao;
    }
    
    public void setDataDevolucao(Date dataDevolucao) {
        this.dataDevolucao = dataDevolucao;
    }
    public Date getDataDevolucaoReal() {
        return this.dataDevolucaoReal;
    }
    
    public void setDataDevolucaoReal(Date dataDevolucaoReal) {
        this.dataDevolucaoReal = dataDevolucaoReal;
    }
    public Set<ProdutosPedido> getProdutosPedidos() {
        return this.produtosPedidos;
    }
    
    public void setProdutosPedidos(Set<ProdutosPedido> produtosPedidos) {
        this.produtosPedidos = produtosPedidos;
    }




}


