package model;
// Generated Jan 6, 2017 6:14:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private Integer idPessoa;
     private String primNome;
     private String sobrenome;
     private String codDocumento;
     private char stPessoa;
     private Set<Contato> contatos = new HashSet<Contato>(0);
     private Fornecedor fornecedor;
     private Cliente cliente;
     private Set<Endereco> enderecos = new HashSet<Endereco>(0);

    public Pessoa() {
    }

	
    public Pessoa(String primNome, char stPessoa) {
        this.primNome = primNome;
        this.stPessoa = stPessoa;
    }
    public Pessoa(String primNome, String sobrenome, String codDocumento, char stPessoa, Set<Contato> contatos, Fornecedor fornecedor, Cliente cliente, Set<Endereco> enderecos) {
       this.primNome = primNome;
       this.sobrenome = sobrenome;
       this.codDocumento = codDocumento;
       this.stPessoa = stPessoa;
       this.contatos = contatos;
       this.fornecedor = fornecedor;
       this.cliente = cliente;
       this.enderecos = enderecos;
    }
   
    public Integer getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(Integer idPessoa) {
        this.idPessoa = idPessoa;
    }
    public String getPrimNome() {
        return this.primNome;
    }
    
    public void setPrimNome(String primNome) {
        this.primNome = primNome;
    }
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }
    public String getCodDocumento() {
        return this.codDocumento;
    }
    
    public void setCodDocumento(String codDocumento) {
        this.codDocumento = codDocumento;
    }
    public char getStPessoa() {
        return this.stPessoa;
    }
    
    public void setStPessoa(char stPessoa) {
        this.stPessoa = stPessoa;
    }
    public Set<Contato> getContatos() {
        return this.contatos;
    }
    
    public void setContatos(Set<Contato> contatos) {
        this.contatos = contatos;
    }
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Set<Endereco> getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set<Endereco> enderecos) {
        this.enderecos = enderecos;
    }




}


