package model;
// Generated Jan 6, 2017 6:14:38 PM by Hibernate Tools 4.3.1



/**
 * ProdutoAtributoId generated by hbm2java
 */
public class ProdutoAtributoId  implements java.io.Serializable {


     private int idProduto;
     private int idAtributo;

    public ProdutoAtributoId() {
    }

    public ProdutoAtributoId(int idProduto, int idAtributo) {
       this.idProduto = idProduto;
       this.idAtributo = idAtributo;
    }
   
    public int getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(int idProduto) {
        this.idProduto = idProduto;
    }
    public int getIdAtributo() {
        return this.idAtributo;
    }
    
    public void setIdAtributo(int idAtributo) {
        this.idAtributo = idAtributo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProdutoAtributoId) ) return false;
		 ProdutoAtributoId castOther = ( ProdutoAtributoId ) other; 
         
		 return (this.getIdProduto()==castOther.getIdProduto())
 && (this.getIdAtributo()==castOther.getIdAtributo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdProduto();
         result = 37 * result + this.getIdAtributo();
         return result;
   }   


}


