package model;
// Generated Dec 13, 2016 10:09:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProdutosPedido generated by hbm2java
 */
public class ProdutosPedido  implements java.io.Serializable {


     private Integer idProdutoPedido;
     private Estoque estoque;
     private Pedido pedido;
     private int quantidade;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public ProdutosPedido() {
    }

	
    public ProdutosPedido(Estoque estoque, Pedido pedido, int quantidade) {
        this.estoque = estoque;
        this.pedido = pedido;
        this.quantidade = quantidade;
    }
    public ProdutosPedido(Estoque estoque, Pedido pedido, int quantidade, Set<Pedido> pedidos) {
       this.estoque = estoque;
       this.pedido = pedido;
       this.quantidade = quantidade;
       this.pedidos = pedidos;
    }
   
    public Integer getIdProdutoPedido() {
        return this.idProdutoPedido;
    }
    
    public void setIdProdutoPedido(Integer idProdutoPedido) {
        this.idProdutoPedido = idProdutoPedido;
    }
    public Estoque getEstoque() {
        return this.estoque;
    }
    
    public void setEstoque(Estoque estoque) {
        this.estoque = estoque;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


