package model;
// Generated Jan 6, 2017 6:14:38 PM by Hibernate Tools 4.3.1



/**
 * ProdutoAtributo generated by hbm2java
 */
public class ProdutoAtributo  implements java.io.Serializable {


     private ProdutoAtributoId id;
     private Atributo atributo;
     private Produto produto;
     private String vlrAtributo;

    public ProdutoAtributo() {
    }

	
    public ProdutoAtributo(ProdutoAtributoId id, Atributo atributo, Produto produto) {
        this.id = id;
        this.atributo = atributo;
        this.produto = produto;
    }
    public ProdutoAtributo(ProdutoAtributoId id, Atributo atributo, Produto produto, String vlrAtributo) {
       this.id = id;
       this.atributo = atributo;
       this.produto = produto;
       this.vlrAtributo = vlrAtributo;
    }
   
    public ProdutoAtributoId getId() {
        return this.id;
    }
    
    public void setId(ProdutoAtributoId id) {
        this.id = id;
    }
    public Atributo getAtributo() {
        return this.atributo;
    }
    
    public void setAtributo(Atributo atributo) {
        this.atributo = atributo;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public String getVlrAtributo() {
        return this.vlrAtributo;
    }
    
    public void setVlrAtributo(String vlrAtributo) {
        this.vlrAtributo = vlrAtributo;
    }




}


