package model;
// Generated Dec 13, 2016 10:09:37 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private Integer idProduto;
     private Categoria categoria;
     private Fornecedor fornecedor;
     private String nomeProduto;
     private String marca;
     private Date dataCadastro;
     private BigDecimal preco;
     private String codProd;
     private String imagem;
     private Set<Estoque> estoques = new HashSet<Estoque>(0);

    public Produto() {
    }

	
    public Produto(Categoria categoria) {
        this.categoria = categoria;
    }
    public Produto(Categoria categoria, Fornecedor fornecedor, String nomeProduto, String marca, Date dataCadastro, BigDecimal preco, String codProd, String imagem, Set<Estoque> estoques) {
       this.categoria = categoria;
       this.fornecedor = fornecedor;
       this.nomeProduto = nomeProduto;
       this.marca = marca;
       this.dataCadastro = dataCadastro;
       this.preco = preco;
       this.codProd = codProd;
       this.imagem = imagem;
       this.estoques = estoques;
    }
   
    public Integer getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(Integer idProduto) {
        this.idProduto = idProduto;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }
    public String getNomeProduto() {
        return this.nomeProduto;
    }
    
    public void setNomeProduto(String nomeProduto) {
        this.nomeProduto = nomeProduto;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public BigDecimal getPreco() {
        return this.preco;
    }
    
    public void setPreco(BigDecimal preco) {
        this.preco = preco;
    }
    public String getCodProd() {
        return this.codProd;
    }
    
    public void setCodProd(String codProd) {
        this.codProd = codProd;
    }
    public String getImagem() {
        return this.imagem;
    }
    
    public void setImagem(String imagem) {
        this.imagem = imagem;
    }
    public Set<Estoque> getEstoques() {
        return this.estoques;
    }
    
    public void setEstoques(Set<Estoque> estoques) {
        this.estoques = estoques;
    }




}


