package model;
// Generated Jan 6, 2017 6:14:38 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private Integer idProduto;
     private Tipo tipo;
     private String nomeProduto;
     private Date dtCadastro;
     private BigDecimal precoVenda;
     private String codProd;
     private String imagem;
     private Character stProduto;
     private Set<VendaItem> vendaItems = new HashSet<VendaItem>(0);
     private Set<Estoque> estoques = new HashSet<Estoque>(0);
     private Set<Fornecedor> fornecedors = new HashSet<Fornecedor>(0);
     private Set<ProdutoAtributo> produtoAtributos = new HashSet<ProdutoAtributo>(0);

    public Produto() {
    }

    public Produto(Tipo tipo, String nomeProduto, Date dtCadastro, BigDecimal precoVenda, String codProd, String imagem, Character stProduto, Set<VendaItem> vendaItems, Set<Estoque> estoques, Set<Fornecedor> fornecedors, Set<ProdutoAtributo> produtoAtributos) {
       this.tipo = tipo;
       this.nomeProduto = nomeProduto;
       this.dtCadastro = dtCadastro;
       this.precoVenda = precoVenda;
       this.codProd = codProd;
       this.imagem = imagem;
       this.stProduto = stProduto;
       this.vendaItems = vendaItems;
       this.estoques = estoques;
       this.fornecedors = fornecedors;
       this.produtoAtributos = produtoAtributos;
    }
   
    public Integer getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(Integer idProduto) {
        this.idProduto = idProduto;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public String getNomeProduto() {
        return this.nomeProduto;
    }
    
    public void setNomeProduto(String nomeProduto) {
        this.nomeProduto = nomeProduto;
    }
    public Date getDtCadastro() {
        return this.dtCadastro;
    }
    
    public void setDtCadastro(Date dtCadastro) {
        this.dtCadastro = dtCadastro;
    }
    public BigDecimal getPrecoVenda() {
        return this.precoVenda;
    }
    
    public void setPrecoVenda(BigDecimal precoVenda) {
        this.precoVenda = precoVenda;
    }
    public String getCodProd() {
        return this.codProd;
    }
    
    public void setCodProd(String codProd) {
        this.codProd = codProd;
    }
    public String getImagem() {
        return this.imagem;
    }
    
    public void setImagem(String imagem) {
        this.imagem = imagem;
    }
    public Character getStProduto() {
        return this.stProduto;
    }
    
    public void setStProduto(Character stProduto) {
        this.stProduto = stProduto;
    }
    public Set<VendaItem> getVendaItems() {
        return this.vendaItems;
    }
    
    public void setVendaItems(Set<VendaItem> vendaItems) {
        this.vendaItems = vendaItems;
    }
    public Set<Estoque> getEstoques() {
        return this.estoques;
    }
    
    public void setEstoques(Set<Estoque> estoques) {
        this.estoques = estoques;
    }
    public Set<Fornecedor> getFornecedors() {
        return this.fornecedors;
    }
    
    public void setFornecedors(Set<Fornecedor> fornecedors) {
        this.fornecedors = fornecedors;
    }
    public Set<ProdutoAtributo> getProdutoAtributos() {
        return this.produtoAtributos;
    }
    
    public void setProdutoAtributos(Set<ProdutoAtributo> produtoAtributos) {
        this.produtoAtributos = produtoAtributos;
    }




}


