package model;
// Generated Dec 13, 2016 10:09:37 PM by Hibernate Tools 4.3.1



/**
 * ValorAtributo generated by hbm2java
 */
public class ValorAtributo  implements java.io.Serializable {


     private Integer idValorAtributo;
     private Atributo atributo;
     private String descricaoValor;
     private int idProduto;

    public ValorAtributo() {
    }

    public ValorAtributo(Atributo atributo, String descricaoValor, int idProduto) {
       this.atributo = atributo;
       this.descricaoValor = descricaoValor;
       this.idProduto = idProduto;
    }
   
    public Integer getIdValorAtributo() {
        return this.idValorAtributo;
    }
    
    public void setIdValorAtributo(Integer idValorAtributo) {
        this.idValorAtributo = idValorAtributo;
    }
    public Atributo getAtributo() {
        return this.atributo;
    }
    
    public void setAtributo(Atributo atributo) {
        this.atributo = atributo;
    }
    public String getDescricaoValor() {
        return this.descricaoValor;
    }
    
    public void setDescricaoValor(String descricaoValor) {
        this.descricaoValor = descricaoValor;
    }
    public int getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(int idProduto) {
        this.idProduto = idProduto;
    }




}


