package model;
// Generated Jan 6, 2017 6:14:38 PM by Hibernate Tools 4.3.1



/**
 * VendaItemAtributoId generated by hbm2java
 */
public class VendaItemAtributoId  implements java.io.Serializable {


     private int idItem;
     private int idAtributo;

    public VendaItemAtributoId() {
    }

    public VendaItemAtributoId(int idItem, int idAtributo) {
       this.idItem = idItem;
       this.idAtributo = idAtributo;
    }
   
    public int getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(int idItem) {
        this.idItem = idItem;
    }
    public int getIdAtributo() {
        return this.idAtributo;
    }
    
    public void setIdAtributo(int idAtributo) {
        this.idAtributo = idAtributo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VendaItemAtributoId) ) return false;
		 VendaItemAtributoId castOther = ( VendaItemAtributoId ) other; 
         
		 return (this.getIdItem()==castOther.getIdItem())
 && (this.getIdAtributo()==castOther.getIdAtributo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdItem();
         result = 37 * result + this.getIdAtributo();
         return result;
   }   


}


