package model;
// Generated Jan 6, 2017 6:14:38 PM by Hibernate Tools 4.3.1



/**
 * VendaItemAtributo generated by hbm2java
 */
public class VendaItemAtributo  implements java.io.Serializable {


     private VendaItemAtributoId id;
     private Atributo atributo;
     private VendaItem vendaItem;
     private String vlrAtributo;

    public VendaItemAtributo() {
    }

	
    public VendaItemAtributo(VendaItemAtributoId id, Atributo atributo, VendaItem vendaItem) {
        this.id = id;
        this.atributo = atributo;
        this.vendaItem = vendaItem;
    }
    public VendaItemAtributo(VendaItemAtributoId id, Atributo atributo, VendaItem vendaItem, String vlrAtributo) {
       this.id = id;
       this.atributo = atributo;
       this.vendaItem = vendaItem;
       this.vlrAtributo = vlrAtributo;
    }
   
    public VendaItemAtributoId getId() {
        return this.id;
    }
    
    public void setId(VendaItemAtributoId id) {
        this.id = id;
    }
    public Atributo getAtributo() {
        return this.atributo;
    }
    
    public void setAtributo(Atributo atributo) {
        this.atributo = atributo;
    }
    public VendaItem getVendaItem() {
        return this.vendaItem;
    }
    
    public void setVendaItem(VendaItem vendaItem) {
        this.vendaItem = vendaItem;
    }
    public String getVlrAtributo() {
        return this.vlrAtributo;
    }
    
    public void setVlrAtributo(String vlrAtributo) {
        this.vlrAtributo = vlrAtributo;
    }




}


